import * as THREE from 'three';
import {flavors} from './flavors';
function label(f){const c=document.createElement('canvas');c.width=1024;c.height=2048;const x=c.getContext('2d');x.fillStyle=f.color;x.fillRect(0,0,1024,2048);x.fillStyle='#161819';x.fillRect(0,0,1024,125);x.fillRect(0,1860,1024,188);x.fillStyle='#ffffff22';for(let i=-1800;i<2200;i+=145){x.save();x.translate(512,1024);x.rotate(-.4);x.fillRect(-1400,i,2800,16);x.restore()}x.save();x.translate(510,1090);x.rotate(-Math.PI/2);x.fillStyle='#111311';x.font='900 italic 300px Arial';x.textAlign='center';x.scale(1.08,1.1);x.fillText('KODEZ',0,110);x.restore();x.fillStyle='#111311';x.textAlign='center';x.font='900 100px Arial';x.fillText('FIZZ',510,1530);x.font='700 39px Arial';x.fillText(f.lines.join(' / '),512,1680);x.font='600 28px Arial';x.fillText('SPARKLING PERSONALITY',512,1770);x.fillStyle='#eef1e3';x.font='700 32px Arial';x.fillText('330 ML  •  ORIGINAL SERIES',512,1950);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t;}

export function createScene(host,state,onError){
const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0x000000,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.append(renderer.domElement);const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,0,12);
const envScene=new THREE.Scene();envScene.background=new THREE.Color('#777b7a');for(const [pos,scale,intensity]of [[[0,5,0],[8,1,6],4],[[-4,0,2],[1,9,5],5],[[4,1,1],[1,7,4],3],[[0,0,-5],[6,8,1],.4]]){const panel=new THREE.Mesh(new THREE.BoxGeometry(...scale),new THREE.MeshBasicMaterial({color:new THREE.Color().setScalar(intensity)}));panel.position.set(...pos);envScene.add(panel)}const pmrem=new THREE.PMREMGenerator(renderer);const env=pmrem.fromScene(envScene,.06);scene.environment=env.texture;pmrem.dispose();scene.add(new THREE.HemisphereLight(0xffffff,0x22252a,2));const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(-3,5,6);scene.add(key);const rim=new THREE.PointLight(0xb494ff,28,20);rim.position.set(3,1,3);scene.add(rim);
const metal=new THREE.MeshStandardMaterial({color:'#c8d0cc',metalness:1,roughness:.23});const darkMetal=new THREE.MeshStandardMaterial({color:'#777f7b',metalness:.95,roughness:.32});
const points=[[.47,-1.65],[.49,-1.62],[.50,-1.56],[.55,-1.48],[.58,-1.35],[.58,1.29],[.56,1.40],[.50,1.51],[.48,1.58]].map(([x,y])=>new THREE.Vector2(x,y));const bodyGeo=new THREE.LatheGeometry(points,80);const cans=flavors.map((f,i)=>{const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({map:label(f),metalness:.55,roughness:.29});g.add(new THREE.Mesh(bodyGeo,mat));for(const y of [-1.61,1.59]){const edge=new THREE.Mesh(new THREE.TorusGeometry(.485,.032,12,64),metal);edge.rotation.x=Math.PI/2;edge.position.y=y;g.add(edge);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.477,.477,.028,64),metal);cap.position.y=y;g.add(cap)}const groove=new THREE.Mesh(new THREE.TorusGeometry(.38,.012,8,64),darkMetal);groove.rotation.x=Math.PI/2;groove.position.y=1.615;g.add(groove);const tab=new THREE.Mesh(new THREE.TorusGeometry(.105,.037,10,32),darkMetal);tab.rotation.x=Math.PI/2;tab.scale.set(.7,1.3,1);tab.position.set(0,1.645,.06);g.add(tab);g.rotation.y=Math.PI;g.position.x=(i-2)*2;scene.add(g);return g;});
// Tiny refractive-looking glints add depth without a video or baked animation.
const specks=new THREE.BufferGeometry();const positions=new Float32Array(120*3);for(let i=0;i<positions.length;i++)positions[i]=(Math.random()-.5)*22;specks.setAttribute('position',new THREE.BufferAttribute(positions,3));const particles=new THREE.Points(specks,new THREE.PointsMaterial({color:0xf5f8de,size:.017,transparent:true,opacity:.45}));scene.add(particles);

let w=innerWidth,h=innerHeight;function resize(){w=innerWidth;h=innerHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.position.z=w<700?15.7:12;camera.updateProjectionMatrix()}resize();addEventListener('resize',resize);
let pointer=0;const onPointer=e=>pointer=(e.clientX/w-.5)*.22;host.addEventListener('pointermove',onPointer);const clock=new THREE.Clock();let elapsed=0,raf;const lerp=THREE.MathUtils.lerp;
function frame(){raf=requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);if(document.hidden)return;const {selected,paused,tab}=state.current;if(!paused)elapsed+=dt;const mobile=w<700;const damping=paused?1:1-Math.exp(-dt*8);rim.color.set(flavors[selected].color);const vh=2*Math.tan(THREE.MathUtils.degToRad(17))*camera.position.z,vw=vh*camera.aspect;
if(tab==='collection'){
 host.style.opacity='1';host.style.pointerEvents='none';particles.visible=false;
 const panels=[...document.querySelectorAll('.chapter')];
 cans.forEach((g,i)=>{const rect=panels[i]?.getBoundingClientRect();if(!rect)return;const center=rect.top+(mobile?rect.height*.73:rect.height*.5);const distance=(center-h*.5)/h;g.visible=Math.abs(distance)<1.25;if(!g.visible)return;const scale=mobile?1.05:1.4;g.scale.setScalar(scale);g.position.set(mobile?0:vw*.24,-distance*vh,0);g.rotation.set(.15,Math.PI+(paused?0:distance*.85+Math.sin(elapsed*.6)*.1),-.12+(paused?0:distance*.18));});
}else{
 const heroH=document.querySelector('.hero')?.offsetHeight||h;const faqStart=document.querySelector('#faq')?.offsetTop||heroH+950;const scroll=scrollY;const progress=THREE.MathUtils.smoothstep(scroll,heroH*.35,heroH*.95);const exit=THREE.MathUtils.smoothstep(scroll,faqStart-h*.7,faqStart-h*.05);host.style.opacity=String(1-exit);host.style.pointerEvents=scroll>heroH*.4?'none':'auto';if(exit>=1)return;
 cans.forEach((g,i)=>{const offset=(i-selected+9)%6-3,active=offset===0;const x0=offset*(mobile?1.72:1.85);const heroY=-(heroH*.50-scroll-h*.5)*vh/h;const storyCenter=mobile?heroH+740:heroH+455;const storyY=-(storyCenter-scroll-h*.5)*vh/h;const x=lerp(x0,active?(mobile?0:vw*.25):x0*2.6,progress);const y=lerp(heroY+(active?0:-.17),storyY,progress)+(paused?0:Math.sin(elapsed*1.2+i)*.07);g.position.x=lerp(g.position.x,x,damping);g.position.y=lerp(g.position.y,y,damping);g.position.z=lerp(g.position.z,active?1.1:-(Math.abs(offset)*.6),damping);const s=active?lerp(mobile?.92:1.05,mobile?1.15:1.45,progress):.88;g.scale.setScalar(lerp(g.scale.x,s,damping));g.rotation.z=lerp(g.rotation.z,active?lerp(-.15,.22,progress):offset*.055,damping);g.rotation.x=lerp(g.rotation.x,active?.13:.08,damping);g.rotation.y=lerp(g.rotation.y,Math.PI+(active?pointer+progress*.9:offset*.85)+(paused?0:Math.sin(elapsed*.6+i)*.08),damping);g.visible=active||progress<.98;});
 particles.rotation.y=elapsed*.012;particles.visible=progress<.8;
}
renderer.render(scene,camera)}frame();
const lost=e=>{e.preventDefault();onError('3D view paused. Reload to restore it.')};renderer.domElement.addEventListener('webglcontextlost',lost);
return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);host.removeEventListener('pointermove',onPointer);renderer.domElement.removeEventListener('webglcontextlost',lost);const geo=new Set(),mats=new Set(),textures=new Set();scene.traverse(o=>{if(o.geometry)geo.add(o.geometry);if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){mats.add(m);if(m.map)textures.add(m.map)}}});geo.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());env.dispose();envScene.traverse(o=>{o.geometry?.dispose();o.material?.dispose()});renderer.dispose();renderer.domElement.remove()};
}
